### PR TITLE
Adds method to generate a UUID

### PR DESCRIPTION
**Pull request by vpratfr**
I needed the same thing as in #42 so here is a PR.

This should avoid to litter the application code with calls to `Uuid::uuid1()` in case later on there is an opportunity to switch to UUID v4 for instance.

- `Model::generateUuid()` generates a Uuid in binary form (ready for use as the `->uuid` attribute)
- `Model::generateUuid(true)` generates a Uuid in string form (ready for use as the `->uuid_text` attribute)

Tests are provided too.

### CODE REVIEW

**Comment by brendt** [comment]
Great! Any reason for the `asText` boolean flag? I'd prefer not to have that one, and just always return `static::encodeUuid($uuid)`

**Comment by vpratfr** [comment]
Because in some cases you want the string representation of the UUID and not the binary version. So it allows to skip the string conversion method that would otherwise need to be added.

By default it returns something ready to be used in the column though.

**Comment by brendt** [comment]
Right. However, if you'd want a textual UUID, you can always generate one with the Ramsey package, I don't see a real need for this package to be concerned with generating those textual UUIDs 🤔

edit: generating textual UUIDs for the outside, that is*

**Comment by vpratfr** [comment]
Package is using uuid v1 internally, but nothing prevents from making this configurable to use v4 or something else.

So the end user would only have a single entry point to get uuids in whichever version the package is using internally.

This is could be useful when writing tests too.

Could be another function however if it is just the parameter that bothers you.

Like generateUuidText for instance

**Comment by brendt** [comment]
I'm not sure if it should be this package's concern. Could you give an example on how it'll improve writing tests?

**Comment by vpratfr** [comment]
It is just a convenient shortcut.

```
$textualUuid = MyModel::generateUuid(true);
// ....
$this->assertEquals("/my-model/$textualUuid", $url);
```

vs

```
$textualUuid = MyModel::decodeUuid(MyModel::generateUuid());
// ....
$this->assertEquals("/my-model/$textualUuid", $url);
```

As I said, this is not a must, this is just a nice convenient shortcut offered to the user. (just like Laravel helpers : str_xxx VS Str::xxx).

No worries if you want to remove the parameter and the corresponding if branch on merge.

**Comment by brendt** [comment]
Yeah, I'd drop it for now. Feel free to make the needed changes, I'll merge this afterwards.

**Comment by vpratfr** [comment]
Done ;)

**Comment by brendt** [comment]
@vpratfr could you take a look at the conflicts? I'd like to merge this one :) (sorry for the delay)

**Comment by vpratfr** [comment]
Hi,

I don't have much time currently to work on this. However, a quick look at the conflict shows that it should take around 2s for you to resolve it when merging (looks like the test before mine got renamed + updated and git got confused by that). Else I can do that most probably next week (if not, that will be post holiday, end of August). Sorry.

**Comment by brendt** [comment]
No problem, I understand!

**Comment by vpratfr** [comment]
Should be fine now. All tests green.

**Comment by brendt** [comment]
Thanks, what's up with the changes to the README? Are these from merging master? Have you tried rebasing instead of mering?

Edit: I pressed a keyboard shortcut which closed this PR, my bad 😳

**Comment by vpratfr** [comment]
Just updated the README to remove references to the deprecated trait (which anyway is empty now). Hence no need to have that in the docs I guess.

**Comment by brendt** [comment]
Right, but it has nothing to do with this PR, right? Also the `: void` return type on the suffix method shouldn't belong in this PR. Sorry for the inconvenience, I know it's meant for the best; but we prefer to keep PRs concise and to the point.

**Comment by vpratfr** [comment]
Reverted them

**Comment by isocroft** [comment]
@vpratfr are you done with the needed changes for this PR to have it merged or you might resubmit ?

**Comment by vpratfr** [comment]
Should all be good.

**Comment by brendt** [comment]
Awesome, thanks!

**Pull request merged**
