### PR TITLE
Add some eloquent-ness to the trait

### PR DESCRIPTION
**Pull request by vpratfr**
Update the find and findMany methods to work with textual versions of the UUIDs.

### CODE REVIEW

**Comment by vpratfr** [comment]
Related to #44 

I do not see any real issue that could arise from that.

Another less invasive way to provide that feature would be an extra trait that can be added on a per-model basis and which contains those 2 methods. Does not feel as smooth from the DX (developer experience) though.

**Comment by brendt** [comment]
I like the functionality, though am a little uncertain of changing such a core Laravel feature. I also briefly mentioned it in #44. 

I'd like to hear @freekmurze 's opinion on it: are you ok with overriding `find` and `findMany` to support textual UUID queries? If so, keep those methods in the main trait, or use a separate one?

My preference is to go with this, in the same trait. I'd hate to see all small things be split in several traits. As you say, @vpratfr; that not really developer-friendly.

**Comment by lonnylot** [comment]
I'd like to make the suggestion to use an `is_int` check and bubbling up to default Eloquent method if it is an int.

Doing so reduces risk and, as far as I'm aware, has no downside. It will also cover a case where a model may have both an auto increment ID _and_ a binary/string UUID.

**Comment by vpratfr** [comment]
That would indeed make it safe. Any comments on Spatie's side?

**Comment by brendt** [comment]
Good idea!

fyi: pretty busy at the moment, so I probably won't be able to merge this PR this week, sorry!

**Comment by vpratfr** [comment]
On holiday. So will work on that one late August or early september.

**Comment by lonnylot** [comment]
I ended up looking into the idea of bubbling up the method call if it was an integer. The default `find` method will use the `getKeyName` method which will return `uuid` and _not_ `id`. For me, it's starting to look more complicated than it's worth. I rescind my suggestion, but if any of you feel it's worthwhile then by all means go for it.

Separately, I was using this branch and found an issue. I've created a [PR](https://github.com/vpratfr/laravel-binary-uuid/pull/1) on @vpratfr branch. I thought I'd note that PR here in case someone else comes across the issue before it's merged.

**Comment by afraca** [comment]
What would be a nice benefit I think is the implicit model binding for the routing then suddenly works, would it not?

**Comment by lewiswharf** [comment]
What's the best way to implement this in the meantime (prior to the commit)?

**Comment by brendt** [comment]
I'd like to merge this as soon as possible. I realise there are more features that can be here, but let's not keep these changes waiting for them. Is that ok for you @vpratfr ?

**Comment by vpratfr** [comment]
Let me merge the pr from @lonnylot first. Then all good.

**Comment by vpratfr** [comment]
All good for me now

**Comment by lewiswharf** [comment]
Thanks @vpratfr and @brendt !

**Comment by brendt** [comment]
Great, thanks guys! I'll tag this soon.

**Comment by afraca** [comment]
Just curious and to be sure: this wouldn't conflict with  https://github.com/spatie/laravel-query-builder  right?

**Comment by brendt** [comment]
@afraca As far as I can tell, it won't. The query builder package adds some convenience features which uses Laravel's query builder, and should perfectly work with another Builder implementation.

**Comment by vpratfr** [comment]
@afraca Not sure why it would. And if it would, there should be a workaround that could be implemented at the application level to make both work together. Will be happy to know the result of your tests. Can you report here or in a new issue if you find anything?

**Comment by brendt** [comment]
FYI this feature is tagged as 1.3.0: https://github.com/spatie/laravel-binary-uuid/releases/tag/1.3.0

**Comment by afraca** [comment]
I don't expect problems. 

Sorry for the spam, I didn't see changes in the README. Especially given how this would make the implicit model binding work again, I think it's nice to mention. Now someone new might expect an burden with using this package, putting  `withUuid` everywhere.

**Comment by louisl** [comment]
> Now someone new might expect an burden with using this package, putting `withUuid` everywhere.

Please update the readme, I've just started using this today and discovered by accident that I don't need `withUuid` on all my queries. Thanks for the lib!

**Comment by vpratfr** [comment]
You may submit a PR any time

**Pull request merged**
