### PR TITLE
Proposed fixes for issue #66 only

### PR DESCRIPTION
**Pull request by isocroft**
This PR refers to issue #66 which is currently under discussion. I have made changes to _HasBinaryUuid.php_ in line with the ideas shared on the issue tracker.

### CODE REVIEW

**Comment by vpratfr** [comment]
Hi,

I see you have tests for #65 but no tests for #66. Don't forget to add some.

Additionnally, I know at Spatie they are quite strict about keeping PRs focused on a single topic. Please make 2 separate PRs (for #66 and #65)

**Comment by isocroft** [comment]
> 
> 
> Hi,
> 
> I see you have tests for #65 but no tests for #66. Don't forget to add some.
> 
> Additionnally, I know at Spatie they are quite strict about keeping PRs focused on a single topic. Please make 2 separate PRs (for #66 and #65)

Yes, i have made the PR focused on issue #66 only. Also, i have added test

**Comment by isocroft** [comment]
All done! @vpratfr

**Comment by isocroft** [comment]
Any reason why this PR isn't merged ?

**Comment by brendt** [comment]
Because I really don't have the time to go through this in depth 😞 @vpratfr does this look ok to you? Can I merge this?

**Comment by vpratfr** [comment]
Looks ok when reading the code. I had/have no time for real testing though. 

On a side note, we have rolled back to standard ids in our current project (lots of complications due to UUIDs when interacting with other packages, in particular Nova & co.). So I am currently not using it anymore :(

**Comment by freekmurze** [comment]
This package has been abandoned. Alternatives: https://github.com/michaeldyrynda/laravel-efficient-uuid & https://github.com/michaeldyrynda/laravel-model-uuid

**Pull request closed without merging**
